
apiVersion: v1
kind: Namespace
metadata:
  name: webservice
  labels:
    name: webservice
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: webservice
  name: webservice-deployment
  labels:
    app: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
        namespace: webservice
    spec:
      containers:
        - name: webservice
          image: 692859929342.dkr.ecr.us-east-1.amazonaws.com/common-app:0.1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 3
            timeoutSeconds: 2