---
apiVersion: v1
kind: Service
metadata:
  namespace: webservice
  name: webservice-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip" 
spec:
  type: LoadBalancer
  selector:
    app: webservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
