name: webservice image - build and push
on:
  push:
    branches:
      - main
    paths:
      - 'webservice/**'
      - '.github/workflows/_webservice.yml'
      - '.github/workflows/webservice.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'webservice/**'
      - '.github/workflows/_webservice.yml'
      - '.github/workflows/webservice.yml'
  workflow_dispatch:
jobs:
  webservice:
    uses: 7sergaza7/webservice/.github/workflows/_webservice.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      